apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-keyvault-aspnetcore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-keyvault-aspnetcore-pod
  template:
    metadata:
      labels:
        app: aks-keyvault-aspnetcore-pod
    spec:
      containers:
      - name: aks-keyvault-aspnetcore-pod
        image: YOUR-ACR.azurecr.io/aspnet-keyvault
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        env:
        # Set an environment var to the cert path for
        # the application to use.
        - name: HTTPS_CERTIFICATE_PATH
          value: "/certs/https.pfx.base64"
        volumeMounts:
        # Mount the key vault volume to /certs
        - name: aks-keyvault-aspnetcore-httpscert
          mountPath: /certs
          readOnly: true
        resources:
          requests:
            cpu: 250m
          limits:
            memory: 500Mi
            cpu: 1
      volumes:
      - name: aks-keyvault-aspnetcore-httpscert
        flexVolume:
          driver: "azure/kv"
          secretRef:
            name: kvcreds
          options:
            # update with your key vault name
            keyvaultname: "YOUR KEY VAULT NAME"
            # update with your AAD tenant
            tenantid: "YOUR KEY VAULT TENANT"
            # The name of the object in Key Vault
            keyvaultobjectnames: "aks-https"
            # Use "secret" to get the full cert
            keyvaultobjecttypes: secret
            # This becomes the file name on the mount.
            keyvaultobjectaliases: "https.pfx.base64"
---
apiVersion: v1
kind: Service
metadata:
  name: aks-keyvault-aspnetcore-svc
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  selector:
    app: aks-keyvault-aspnetcore-pod
